# Generated by Django 4.1 on 2024-08-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorType',
            fields=[
                ('name', models.CharField(choices=[('USER', 'User'), ('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic')],
                                          max_length=20, primary_key=True, serialize=False, unique=True)),
                ('is_human', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatai.authortype')),
                ('conversation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatai.conversation')),
            ],
        ),
    ]
