# Generated by Django 4.1 on 2024-08-29 15:13
from linecache import cache

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chatai', '0001_initial'),
    ]

    operations = []
