# Generated by Django 4.1 on 2024-08-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0002_auto_20240829_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authortype',
            name='is_human',
        ),
    ]
