# Generated by Django 4.1 on 2024-08-29 15:22

from django.db import migrations


def populate_author_types(apps, schema_editor):
    AuthorType = apps.get_model('chatai', 'AuthorType')
    print(AuthorType)
    AuthorTypeChoices = AuthorType._meta.get_field('name').choices
    print(AuthorTypeChoices)
    for choice in AuthorTypeChoices:
        AuthorType.objects.create(name=choice[0])


class Migration(migrations.Migration):
    dependencies = [
        ('chatai', '0003_remove_authortype_is_human'),
    ]

    operations = [
        migrations.RunPython(populate_author_types),
    ]
